export const MONITOR_ENDPOINTS_CONSTANTS = {
  CREATE_MONITOR: 'CREATE_MONITOR'
}

export type MONITOR_VALIDATOR_ENDPOINTS_TYPES = typeof MONITOR_ENDPOINTS_CONSTANTS[keyof typeof MONITOR_ENDPOINTS_CONSTANTS];