export const MONITOR_ENDPOINTS_CONSTANTS = {
  CREATE_MONITOR: 'CREATE_MONITOR',
  GET_ONE_MONITOR: 'GET_ONE_MONITOR',
  UPDATE_MONITOR: 'UPDATE_MONITOR',
  DELETE_MONITOR: 'DELETE_MONITOR'
}

export type MONITOR_VALIDATOR_ENDPOINTS_TYPES = typeof MONITOR_ENDPOINTS_CONSTANTS[keyof typeof MONITOR_ENDPOINTS_CONSTANTS];