export const CRON_JOBS = {
  REGULAR_MONITOR_CHECK: 'REGULAR_MONITOR_CHECK',
  REGULAR_SERVER_HEALTH_CHECK: 'REGULAR_SERVER_HEALTH_CHECK',
  RECENT_ERROR_REPORTS_MONITOR_REMOVAL: 'RECENT_ERROR_REPORTS_MONITOR_REMOVAL'
}

export type CRON_JOB_TYPES = typeof CRON_JOBS[keyof typeof CRON_JOBS];
